dict_en_cz = {
    "new_game": ["New game", "Nová hra"],
    "settings": ["Settings", "Nastavení"],
    "number_of_packages": ["Number of packages: ", "Počet balíčků: "],
    "budget": ["Budget: ", "Rozpočet: "],
    "strategy": ["Basic strategy panel: ", "Panel základní strategie: "],
    "language": ["Language: ", "Jazyk: "],
    "author": ["Author", "Autor"],
    "created_by": ["Created by: ", "Vytvořil: "],
    "save_and_back": ["Save and go back", "Ulož a jdi zpět"],
    "close": ["Close", "Zavřít"],
    "quit": ["Quit", "Odejít"],
    "on_off": ["On/Off", "Zapnout/Vypnout"],
    "hit_button_note": ["Draw a new card.", "Vezmi další kartu."],
    "stand_button_note": ["No next card.", "Stačí, už nechci další kartu."],
    "double_button_note": ["Double your bet and draw one extra card.", "Zdvojnásob sázku a vezmi poslední kartu."],
    "split_button_note": ["Split your card into new two decks.", "Rozděl své karty do dvou nových balíčků."],
    "insurance_button_note": ["Insure yourself against dealer´s '21' in a ratio of 2:1.", "Pojistěte se proti dealerově '21' v poměru 2:1."],
    "deal_button_note":["Deal a new hand.","Rozdej nové karty."],
    "want_quit": ["Do you want to quit?", "Opravdu chceš odejít?"],
    "your": ["Your", "Tvůj"],
    "lose": ["Lose!", "Prohra!"],
    "win": ["Win!", "Výhra!"],
    "draw": ["Draw!", "Remíza!"],
}
